version: '3.7'
services:
  db:
    image: jdanussi/postgres-db:v1
    build:
      context: ./postgres-db
      dockerfile: Dockerfile
    container_name: postgres-db
    hostname: postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
     - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql:/sql

networks:
  default:
    name: covid19_net
